# Submission script
# DO NOT EDIT THIS FILE

import tarfile, re, os

solution_filename = 'solution-lean.tar.gz'
t = tarfile.open(solution_filename, 'w:gz')
error = False
def try_add(f, default_len = 0, must_contain_strs = [], must_contain_num = 1):
    global error
    try:
        s = os.stat(f)
        if default_len != 0 and s.st_size == default_len:
            print(f"Warning: did you complete {f}?")
        if f == 'README.txt':
            for l in open("README.txt").readlines():
                if re.match('^id:\\s*\d{8}\\s*$', l):
                    break
            else:
                print(f"Error: your id is not found in {f}")
                error = True
        for must_word in must_contain_strs:
            contents = open(f, 'r').read()
            freq = len(re.findall(must_word, contents))
            if freq < must_contain_num:
                print(f'Error: word "{must_word}" does not',
                      f'appear >={must_contain_num} times in {f}.')
                error = True

        t.add(f, arcname=os.path.basename(f))
    except FileNotFoundError:
        print(f"Error: missing {f}")
        error = True

try_add('prob01.lean', 207)
try_add('prob02.lean', 246, ['eval.ELeft', 'eval.ERight', 'eval.EOp'], 1)
try_add('prob03.lean', 577)
try_add('prob04.lean', 240)
try_add('prob05.lean', 254)
try_add('prob06.lean', 243)
try_add('prob07.lean', 263, ['evals.CStep'], 3)
# try_add('prob08.lean', 322)
# try_add('prob09.lean', 236)
# try_add('prob10.lean', 309)
# try_add('prob11.lean', 358)
try_add('README.txt')
t.close()

if not error:
    print(f"Wrote '{solution_filename}'. Upload this file to Canvas.")
else:
    print(f'Try again after fixing the above error(s)!')
